
import fs from 'fs';
import path from 'path';
import { fileURLToPath } from 'url';

const __filename = fileURLToPath(import.meta.url);
const __dirname = path.dirname(__filename);

const basePath = path.resolve(__dirname, 'neurodiversity_complete.json');
const baseData = JSON.parse(fs.readFileSync(basePath, 'utf8'));

// Add remaining paragraphs 2-5 (will add inline to save space)
// Paragraph 2
baseData.content.push({
    "paragraphId": 2,
    "sentences": [
        { "id": 5, "text": "The most common office design trend that neurodiverse design seeks to change is the open-plan office.", "translation": "ニューロダイバースデザインが変えようとしている最も一般的なオフィスデザインのトレンドは、オープンプランオフィスである。", "grammarAnalysis": { "mainVerbs": ["is"], "structureHtml": "<span class='chunk S-group'><span class='text'>The most common office design trend (that <span class='chunk S2-group'><span class='text'>neurodiverse design</span><span class='tag'>S'</span></span> <span class='chunk V2-group'><span class='text'>seeks to change</span><span class='tag'>V'</span></span>)</span><span class='tag'>S</span></span> <span class='chunk V-group'><span class='text'>is</span><span class='tag'>V</span></span> <span class='chunk C-group'><span class='text'>the open-plan office</span><span class='tag'>C</span></span>.", "translationHtml": "<span class='t-S'>最も一般的なオフィスデザインのトレンドは</span> <span class='t-V'>である</span> <span class='t-C'>オープンプランオフィス</span>。", "naturalTranslation": "ニューロダイバースデザインが変えようとしている最も一般的なオフィスデザインのトレンドは、オープンプランオフィスである。", "vocabulary": [{ "word": "seeks to", "meaning": "〜しようとする" }], "grammarNotes": [{ "phrase": "that neurodiverse design seeks to change", "explanation": "<b>関係代名詞節構造</b>:<ul><li><b>S'</b>: neurodiverse design</li><li><b>V'</b>: seeks to change</li></ul>trendを修飾。" }] } },
        { "id": 6, "text": "Originally promoted as a way to encourage collaboration and transparency, this layout is based on the sensory tolerance of the \"neurotypical\" or average person.", "translation": "もともとコラボレーションと透明性を促進する方法として推進されていたこのレイアウトは、「定型発達」または平均的な人の感覚的許容度に基づいている。", "grammarAnalysis": { "mainVerbs": ["is based"], "structureHtml": "<span class='chunk M-group'><span class='text'>(Originally promoted as a way to encourage collaboration and transparency)</span><span class='tag'>M</span></span>, <span class='chunk S-group'><span class='text'>this layout</span><span class='tag'>S</span></span> <span class='chunk V-group'><span class='text'>is based</span><span class='tag'>V</span></span> <span class='chunk M-group'><span class='text'>(on the sensory tolerance of the \"neurotypical\" or average person)</span><span class='tag'>M</span></span>.", "translationHtml": "<span class='t-M'>(もともと推進されていた)</span>、<span class='t-S'>このレイアウトは</span> <span class='t-V'>基づいている</span>。", "naturalTranslation": "もともとコラボレーションと透明性を促進する方法として推進されていたこのレイアウトは、「定型発達」または平均的な人の感覚的許容度に基づいている。", "vocabulary": [{ "word": "transparency", "meaning": "透明性" }, { "word": "sensory tolerance", "meaning": "感覚的許容度" }, { "word": "neurotypical", "meaning": "定型発達の" }], "grammarNotes": [{ "phrase": "Originally promoted as", "explanation": "<b>過去分詞による分詞構文</b>: 背景を表す。" }, { "phrase": "is based on", "explanation": "<b>be based on</b>: 「〜に基づいている」。" }] } },
        { "id": 7, "text": "For the majority of workers, the background hum of conversation and bright fluorescent lighting may be manageable annoyances.", "translation": "大多数の労働者にとって、会話のバックグラウンドノイズや明るい蛍光灯は、対処可能な煩わしさかもしれない。", "grammarAnalysis": { "mainVerbs": ["may be"], "structureHtml": "<span class='chunk M-group'><span class='text'>(For the majority of workers)</span><span class='tag'>M</span></span>, <span class='chunk S-group'><span class='text'>the background hum of conversation and bright fluorescent lighting</span><span class='tag'>S</span></span> <span class='chunk V-group'><span class='text'>may be</span><span class='tag'>V</span></span> <span class='chunk C-group'><span class='text'>manageable annoyances</span><span class='tag'>C</span></span>.", "translationHtml": "<span class='t-M'>(大多数の労働者にとって)</span>、<span class='t-S'>バックグラウンドノイズや蛍光灯は</span> <span class='t-V'>かもしれない</span> <span class='t-C'>対処可能な煩わしさ</span>。", "naturalTranslation": "大多数の労働者にとって、会話のバックグラウンドノイズや明るい蛍光灯は、対処可能な煩わしさかもしれない。", "vocabulary": [{ "word": "background hum", "meaning": "バックグラウンドノイズ" }, { "word": "fluorescent lighting", "meaning": "蛍光灯" }, { "word": "manageable", "meaning": "対処可能な" }], "grammarNotes": [{ "phrase": "may be", "explanation": "<b>助動詞may</b>: 推量。" }] } },
        { "id": 8, "text": "However, for individuals who are hypersensitive to sensory stimuli—a common trait among neurodivergent people—these elements can be overwhelming, leading to severe anxiety and reduced productivity.", "translation": "しかし、感覚刺激に過敏な人々—神経発達症の人々に共通する特性—にとって、これらの要素は圧倒的なものとなり、深刻な不安や生産性の低下を招く可能性がある。", "grammarAnalysis": { "mainVerbs": ["can be"], "structureHtml": "<span class='chunk M-group'><span class='text'>(However)</span><span class='tag'>M</span></span>, <span class='chunk M-group'><span class='text'>(for individuals who are hypersensitive—...—)</span><span class='tag'>M</span></span>, <span class='chunk S-group'><span class='text'>these elements</span><span class='tag'>S</span></span> <span class='chunk V-group'><span class='text'>can be</span><span class='tag'>V</span></span> <span class='chunk C-group'><span class='text'>overwhelming</span><span class='tag'>C</span></span>, <span class='chunk M-group'><span class='text'>(leading to...)</span><span class='tag'>M</span></span>.", "translationHtml": "<span class='t-M'>(しかし)</span>、<span class='t-M'>(過敏な人々にとって)</span>、<span class='t-S'>これらの要素は</span> <span class='t-V'>なりうる</span> <span class='t-C'>圧倒的なものに</span>。", "naturalTranslation": "しかし、感覚刺激に過敏な人々にとって、これらの要素は圧倒的なものとなり、深刻な不安や生産性の低下を招く可能性がある。", "vocabulary": [{ "word": "hypersensitive", "meaning": "過敏な" }, { "word": "sensory stimuli", "meaning": "感覚刺激" }, { "word": "neurodivergent", "meaning": "神経発達症の" }, { "word": "overwhelming", "meaning": "圧倒的な" }], "grammarNotes": [{ "phrase": "who are hypersensitive", "explanation": "<b>関係代名詞節構造</b>:<ul><li><b>S'</b>: who</li><li><b>V'</b>: are hypersensitive</li></ul>" }, { "phrase": "—a common trait—", "explanation": "<b>ダッシュによる挿入</b>: 補足説明。" }, { "phrase": "leading to", "explanation": "<b>分詞構文</b>: 結果を表す。" }] } }
    ]
});

// Paragraph 3
baseData.content.push({
    "paragraphId": 3,
    "sentences": [
        { "id": 9, "text": "Unlike traditional approaches that aim to create a uniform environment for the average employee, neurodiverse design rejects the idea of a \"standard\" user.", "translation": "平均的な従業員のために均一な環境を作ることを目指す従来のアプローチとは異なり、ニューロダイバースデザインは「標準的な」ユーザーという概念を拒否する。", "grammarAnalysis": { "mainVerbs": ["rejects"], "structureHtml": "<span class='chunk M-group'><span class='text'>(Unlike traditional approaches that aim to create...)</span><span class='tag'>M</span></span>, <span class='chunk S-group'><span class='text'>neurodiverse design</span><span class='tag'>S</span></span> <span class='chunk V-group'><span class='text'>rejects</span><span class='tag'>V</span></span> <span class='chunk O-group'><span class='text'>the idea of a \"standard\" user</span><span class='tag'>O</span></span>.", "translationHtml": "<span class='t-M'>(従来のアプローチとは異なり)</span>、<span class='t-S'>ニューロダイバースデザインは</span> <span class='t-V'>拒否する</span> <span class='t-O'>「標準的な」ユーザーという概念を</span>。", "naturalTranslation": "平均的な従業員のために均一な環境を作ることを目指す従来のアプローチとは異なり、ニューロダイバースデザインは「標準的な」ユーザーという概念を拒否する。", "vocabulary": [{ "word": "uniform", "meaning": "均一な" }, { "word": "rejects", "meaning": "拒否する" }], "grammarNotes": [{ "phrase": "Unlike traditional approaches", "explanation": "<b>Unlike</b>: 「〜とは異なり」対比の前置詞。" }, { "phrase": "that aim to create", "explanation": "<b>関係代名詞節</b>: approachesを修飾。" }] } },
        { "id": 10, "text": "Advocates reason that architects can create better workspaces by recognizing that human brains process information differently.", "translation": "支持者たちは、人間の脳が情報を異なる方法で処理することを認識することで、建築家はより良いワークスペースを作れると論じている。", "grammarAnalysis": { "mainVerbs": ["reason"], "structureHtml": "<span class='chunk S-group'><span class='text'>Advocates</span><span class='tag'>S</span></span> <span class='chunk V-group'><span class='text'>reason</span><span class='tag'>V</span></span> <span class='chunk O-group'><span class='text'>that architects can create better workspaces...</span><span class='tag'>O</span></span>.", "translationHtml": "<span class='t-S'>支持者たちは</span> <span class='t-V'>論じている</span> <span class='t-O'>that [建築家はより良いワークスペースを作れると]</span>。", "naturalTranslation": "支持者たちは、人間の脳が情報を異なる方法で処理することを認識することで、建築家はより良いワークスペースを作れると論じている。", "vocabulary": [{ "word": "reason", "meaning": "論じる" }, { "word": "process", "meaning": "処理する" }], "grammarNotes": [{ "phrase": "by recognizing that", "explanation": "<b>by + 動名詞</b>: 手段を表す。" }] } },
        { "id": 11, "text": "They argue that simply forcing neurodivergent employees to adapt to existing structures is ineffective.", "translation": "彼らは、神経発達症の従業員に既存の構造に適応することを単に強制することは効果がないと主張している。", "grammarAnalysis": { "mainVerbs": ["argue"], "structureHtml": "<span class='chunk S-group'><span class='text'>They</span><span class='tag'>S</span></span> <span class='chunk V-group'><span class='text'>argue</span><span class='tag'>V</span></span> <span class='chunk O-group'><span class='text'>that simply forcing... is ineffective</span><span class='tag'>O</span></span>.", "translationHtml": "<span class='t-S'>彼らは</span> <span class='t-V'>主張している</span> <span class='t-O'>that [単に強制することは効果がないと]</span>。", "naturalTranslation": "彼らは、神経発達症の従業員に既存の構造に適応することを単に強制することは効果がないと主張している。", "vocabulary": [{ "word": "forcing ... to adapt", "meaning": "〜に適応を強制する" }, { "word": "ineffective", "meaning": "効果がない" }], "grammarNotes": [{ "phrase": "simply forcing ... to adapt", "explanation": "<b>動名詞</b>: that節内の主語。" }] } },
        { "id": 12, "text": "Instead, they propose a fundamental shift in design thinking: creating flexible environments that offer a variety of sensory experiences, allowing users to choose the setting that best suits their current needs and working style.", "translation": "代わりに、彼らはデザイン思考における根本的な転換を提案している：多様な感覚体験を提供する柔軟な環境を作り、ユーザーが現在のニーズと作業スタイルに最も適した設定を選択できるようにすることである。", "grammarAnalysis": { "mainVerbs": ["propose"], "structureHtml": "<span class='chunk M-group'><span class='text'>(Instead)</span><span class='tag'>M</span></span>, <span class='chunk S-group'><span class='text'>they</span><span class='tag'>S</span></span> <span class='chunk V-group'><span class='text'>propose</span><span class='tag'>V</span></span> <span class='chunk O-group'><span class='text'>a fundamental shift...</span><span class='tag'>O</span></span>: <span class='chunk M-group'><span class='text'>(creating flexible environments...)</span><span class='tag'>M</span></span>.", "translationHtml": "<span class='t-M'>(代わりに)</span>、<span class='t-S'>彼らは</span> <span class='t-V'>提案している</span> <span class='t-O'>根本的な転換を</span>：<span class='t-M'>(柔軟な環境を作り)</span>。", "naturalTranslation": "代わりに、彼らはデザイン思考における根本的な転換を提案している。", "vocabulary": [{ "word": "fundamental shift", "meaning": "根本的な転換" }, { "word": "sensory experiences", "meaning": "感覚体験" }], "grammarNotes": [{ "phrase": ": creating flexible environments", "explanation": "<b>コロン</b>: 前述の具体的説明。" }, { "phrase": "allowing users to choose", "explanation": "<b>分詞構文</b>: 結果を表す。" }] } }
    ]
});

// Paragraph 4
baseData.content.push({
    "paragraphId": 4,
    "sentences": [
        { "id": 13, "text": "One example of putting these values into practice is the inclusion of \"quiet zones\" and \"focus rooms\" in new office builds.", "translation": "これらの価値観を実践する一例は、新しいオフィスビルに「静寂ゾーン」や「集中ルーム」を設けることである。", "grammarAnalysis": { "mainVerbs": ["is"], "structureHtml": "<span class='chunk S-group'><span class='text'>One example of putting these values into practice</span><span class='tag'>S</span></span> <span class='chunk V-group'><span class='text'>is</span><span class='tag'>V</span></span> <span class='chunk C-group'><span class='text'>the inclusion of \"quiet zones\" and \"focus rooms\"...</span><span class='tag'>C</span></span>.", "translationHtml": "<span class='t-S'>一例は</span> <span class='t-V'>である</span> <span class='t-C'>設けること</span>。", "naturalTranslation": "これらの価値観を実践する一例は、新しいオフィスビルに「静寂ゾーン」や「集中ルーム」を設けることである。", "vocabulary": [{ "word": "putting ... into practice", "meaning": "〜を実践する" }, { "word": "inclusion", "meaning": "含めること" }], "grammarNotes": [{ "phrase": "One example of putting these values into practice", "explanation": "<b>動名詞</b>: 前置詞ofの目的語。" }] } },
        { "id": 14, "text": "Architects work closely with neurodivergent employees during the planning phase to identify specific triggers, such as flickering lights or patterned carpets that can cause visual stress.", "translation": "建築家は、計画段階で神経発達症の従業員と緊密に協力し、ちらつく照明や視覚的ストレスを引き起こす可能性のある模様入りカーペットなど、特定のトリガーを特定する。", "grammarAnalysis": { "mainVerbs": ["work"], "structureHtml": "<span class='chunk S-group'><span class='text'>Architects</span><span class='tag'>S</span></span> <span class='chunk V-group'><span class='text'>work closely</span><span class='tag'>V</span></span> <span class='chunk M-group'><span class='text'>(with neurodivergent employees) (during the planning phase) (to identify specific triggers...)</span><span class='tag'>M</span></span>.", "translationHtml": "<span class='t-S'>建築家は</span> <span class='t-V'>緊密に協力する</span> <span class='t-M'>(従業員と)(計画段階で)(トリガーを特定するために)</span>。", "naturalTranslation": "建築家は、計画段階で神経発達症の従業員と緊密に協力し、特定のトリガーを特定する。", "vocabulary": [{ "word": "triggers", "meaning": "トリガー" }, { "word": "flickering lights", "meaning": "ちらつく照明" }, { "word": "patterned carpets", "meaning": "模様入りカーペット" }, { "word": "visual stress", "meaning": "視覚的ストレス" }], "grammarNotes": [{ "phrase": "to identify specific triggers", "explanation": "<b>不定詞</b>: 目的を表す。" }, { "phrase": "that can cause visual stress", "explanation": "<b>関係代名詞節</b>: carpetsを修飾。" }] } },
        { "id": 15, "text": "In response, they might install sound-absorbing materials, adjustable lighting systems, and private pods.", "translation": "それに応じて、彼らは吸音材、調節可能な照明システム、プライベートポッドを設置するかもしれない。", "grammarAnalysis": { "mainVerbs": ["might install"], "structureHtml": "<span class='chunk M-group'><span class='text'>(In response)</span><span class='tag'>M</span></span>, <span class='chunk S-group'><span class='text'>they</span><span class='tag'>S</span></span> <span class='chunk V-group'><span class='text'>might install</span><span class='tag'>V</span></span> <span class='chunk O-group'><span class='text'>sound-absorbing materials, adjustable lighting systems, and private pods</span><span class='tag'>O</span></span>.", "translationHtml": "<span class='t-M'>(それに応じて)</span>、<span class='t-S'>彼らは</span> <span class='t-V'>設置するかもしれない</span> <span class='t-O'>吸音材等を</span>。", "naturalTranslation": "それに応じて、彼らは吸音材、調節可能な照明システム、プライベートポッドを設置するかもしれない。", "vocabulary": [{ "word": "sound-absorbing materials", "meaning": "吸音材" }, { "word": "adjustable", "meaning": "調節可能な" }, { "word": "private pods", "meaning": "プライベートポッド" }], "grammarNotes": [{ "phrase": "In response", "explanation": "<b>In response</b>: 「それに応じて」。" }] } },
        { "id": 16, "text": "In some cases, companies have used virtual reality simulations to allow staff to test and provide feedback on proposed layouts before construction begins, ensuring their unique perspectives are integrated into the final design.", "translation": "場合によっては、企業は建設が始まる前にスタッフが提案されたレイアウトをテストし、フィードバックを提供できるようにするためにバーチャルリアリティシミュレーションを使用し、彼らのユニークな視点が最終設計に統合されることを確実にしている。", "grammarAnalysis": { "mainVerbs": ["have used"], "structureHtml": "<span class='chunk M-group'><span class='text'>(In some cases)</span><span class='tag'>M</span></span>, <span class='chunk S-group'><span class='text'>companies</span><span class='tag'>S</span></span> <span class='chunk V-group'><span class='text'>have used</span><span class='tag'>V</span></span> <span class='chunk O-group'><span class='text'>virtual reality simulations</span><span class='tag'>O</span></span> <span class='chunk M-group'><span class='text'>(to allow staff to test... ensuring...)</span><span class='tag'>M</span></span>.", "translationHtml": "<span class='t-M'>(場合によっては)</span>、<span class='t-S'>企業は</span> <span class='t-V'>使用してきた</span> <span class='t-O'>VRシミュレーションを</span>。", "naturalTranslation": "場合によっては、企業はVRシミュレーションを使用し、スタッフがレイアウトをテストし、フィードバックできるようにしている。", "vocabulary": [{ "word": "virtual reality simulations", "meaning": "VRシミュレーション" }, { "word": "proposed layouts", "meaning": "提案されたレイアウト" }, { "word": "perspectives", "meaning": "視点" }], "grammarNotes": [{ "phrase": "have used", "explanation": "<b>現在完了</b>: 経験。" }, { "phrase": "before construction begins", "explanation": "<b>時の副詞節</b>。" }, { "phrase": "ensuring their unique perspectives are integrated", "explanation": "<b>分詞構文</b>: 結果を表す。" }] } }
    ]
});

// Paragraph 5
baseData.content.push({
    "paragraphId": 5,
    "sentences": [
        { "id": 17, "text": "The impact of neurodiverse design extends beyond just helping a specific group of employees; it is improving the work environment for everyone.", "translation": "ニューロダイバースデザインの影響は、特定の従業員グループを助けることだけにとどまらない。それはすべての人の労働環境を改善している。", "grammarAnalysis": { "mainVerbs": ["extends", "is improving"], "structureHtml": "<span class='chunk S-group'><span class='text'>The impact of neurodiverse design</span><span class='tag'>S</span></span> <span class='chunk V-group'><span class='text'>extends</span><span class='tag'>V</span></span> <span class='chunk M-group'><span class='text'>(beyond just helping...)</span><span class='tag'>M</span></span>; <span class='chunk S-group'><span class='text'>it</span><span class='tag'>S</span></span> <span class='chunk V-group'><span class='text'>is improving</span><span class='tag'>V</span></span> <span class='chunk O-group'><span class='text'>the work environment for everyone</span><span class='tag'>O</span></span>.", "translationHtml": "<span class='t-S'>影響は</span> <span class='t-V'>及ぶ</span>；<span class='t-S'>それは</span> <span class='t-V'>改善している</span> <span class='t-O'>すべての人の労働環境を</span>。", "naturalTranslation": "ニューロダイバースデザインの影響は、特定の従業員グループを助けることだけにとどまらない。", "vocabulary": [{ "word": "extends beyond", "meaning": "〜を超えて及ぶ" }], "grammarNotes": [{ "phrase": "extends beyond just helping", "explanation": "<b>前置詞 + 動名詞</b>。" }, { "phrase": "; it is improving", "explanation": "<b>セミコロン</b>: 関連する文を接続。" }] } },
        { "id": 18, "text": "Although the movement began as a way to address the specific difficulties faced by neurodivergent individuals, its principles have proven universally beneficial.", "translation": "この運動は神経発達症の個人が直面する特定の困難に対処する方法として始まったが、その原則は普遍的に有益であることが証明されている。", "grammarAnalysis": { "mainVerbs": ["have proven"], "structureHtml": "<span class='chunk M-group'><span class='text'>(Although the movement began as...)</span><span class='tag'>M</span></span>, <span class='chunk S-group'><span class='text'>its principles</span><span class='tag'>S</span></span> <span class='chunk V-group'><span class='text'>have proven</span><span class='tag'>V</span></span> <span class='chunk C-group'><span class='text'>universally beneficial</span><span class='tag'>C</span></span>.", "translationHtml": "<span class='t-M'>(運動が〜として始まったが)</span>、<span class='t-S'>その原則は</span> <span class='t-V'>証明されている</span> <span class='t-C'>普遍的に有益である</span>。", "naturalTranslation": "この運動は〜として始まったが、その原則は普遍的に有益であることが証明されている。", "vocabulary": [{ "word": "universally beneficial", "meaning": "普遍的に有益な" }, { "word": "have proven", "meaning": "〜と証明された" }], "grammarNotes": [{ "phrase": "Although the movement began", "explanation": "<b>譲歩のalthough節</b>。" }, { "phrase": "faced by neurodivergent individuals", "explanation": "<b>過去分詞</b>: difficultiesを修飾。" }] } },
        { "id": 19, "text": "By prioritizing flexibility, comfort, and individual choice, this approach empowers all workers to control their environment.", "translation": "柔軟性、快適さ、個人の選択を優先することで、このアプローチはすべての労働者が自分の環境をコントロールできるようにしている。", "grammarAnalysis": { "mainVerbs": ["empowers"], "structureHtml": "<span class='chunk M-group'><span class='text'>(By prioritizing flexibility, comfort, and individual choice)</span><span class='tag'>M</span></span>, <span class='chunk S-group'><span class='text'>this approach</span><span class='tag'>S</span></span> <span class='chunk V-group'><span class='text'>empowers</span><span class='tag'>V</span></span> <span class='chunk O-group'><span class='text'>all workers</span><span class='tag'>O</span></span> <span class='chunk C-group'><span class='text'>to control their environment</span><span class='tag'>C</span></span>.", "translationHtml": "<span class='t-M'>(〜を優先することで)</span>、<span class='t-S'>このアプローチは</span> <span class='t-V'>力を与える</span> <span class='t-O'>すべての労働者に</span>。", "naturalTranslation": "柔軟性、快適さ、個人の選択を優先することで、このアプローチはすべての労働者が環境をコントロールできるようにしている。", "vocabulary": [{ "word": "prioritizing", "meaning": "優先する" }, { "word": "empowers", "meaning": "力を与える" }], "grammarNotes": [{ "phrase": "By prioritizing", "explanation": "<b>By + 動名詞</b>: 手段を表す。" }, { "phrase": "empowers all workers to control", "explanation": "<b>empower O to do</b>: 「Oが〜できるようにする」。" }] } },
        { "id": 20, "text": "As a result, companies are discovering that spaces designed with neurodiversity in mind often lead to higher overall satisfaction and productivity across the entire workforce.", "translation": "その結果、企業は、ニューロダイバーシティを念頭に置いて設計された空間が、全従業員にわたってより高い総合的な満足度と生産性につながることが多いことを発見している。", "grammarAnalysis": { "mainVerbs": ["are discovering"], "structureHtml": "<span class='chunk M-group'><span class='text'>(As a result)</span><span class='tag'>M</span></span>, <span class='chunk S-group'><span class='text'>companies</span><span class='tag'>S</span></span> <span class='chunk V-group'><span class='text'>are discovering</span><span class='tag'>V</span></span> <span class='chunk O-group'><span class='text'>that spaces designed... often lead to higher overall satisfaction...</span><span class='tag'>O</span></span>.", "translationHtml": "<span class='t-M'>(その結果)</span>、<span class='t-S'>企業は</span> <span class='t-V'>発見している</span> <span class='t-O'>that [空間が〜につながることを]</span>。", "naturalTranslation": "その結果、企業は、ニューロダイバーシティを念頭に置いて設計された空間が満足度と生産性につながることを発見している。", "vocabulary": [{ "word": "with neurodiversity in mind", "meaning": "ニューロダイバーシティを念頭に置いて" }, { "word": "lead to", "meaning": "〜につながる" }, { "word": "overall satisfaction", "meaning": "総合的な満足度" }], "grammarNotes": [{ "phrase": "As a result", "explanation": "<b>As a result</b>: 「その結果」結論を導く。" }, { "phrase": "designed with neurodiversity in mind", "explanation": "<b>過去分詞</b>: spacesを修飾。" }] } }
    ]
});

// Add questions
baseData.questions = [
    { "id": 1, "text": "What led to the emergence of the neurodiverse design movement?", "textTranslation": "ニューロダイバースデザイン運動の出現につながったのは何ですか？", "choices": [{ "id": 1, "text": "A decrease in the number of companies willing to adopt open-plan office layouts due to high costs.", "translation": "高コストのためオープンプランオフィスのレイアウトを採用しようとする企業の数が減少したこと。", "isCorrect": false }, { "id": 2, "text": "The realization that standard office environments were often unsuitable for employees with neurological differences.", "translation": "標準的なオフィス環境が神経学的差異を持つ従業員には適していないことが多いという認識。", "isCorrect": true, "highlight": "standard office environments were often unsuitable" }, { "id": 3, "text": "A desire among architects to return to more traditional, private office designs from the past.", "translation": "建築家の間で過去のより伝統的でプライベートなオフィスデザインに戻りたいという願望。", "isCorrect": false }, { "id": 4, "text": "The discovery that neurotypical employees were also dissatisfied with the noise levels in open offices.", "translation": "定型発達の従業員もオープンオフィスの騒音レベルに不満を持っていたという発見。", "isCorrect": false }], "hint": { "paragraphId": 1, "description": "第1段落。この運動がなぜ出現したかについて述べている部分を探しましょう。", "targetSentenceId": 3, "highlightWord": "fail to accommodate employees with neurological differences", "highlightWordSentenceId": 3 }, "keywords": ["led to", "emergence", "neurodiverse design movement"], "keywordExplanations": { "led to": "「〜につながった」。原因を問う表現。", "emergence": "出現。" }, "keywordMatches": [{ "sentenceId": 2, "text": "has emerged", "keyword": "emergence" }, { "sentenceId": 3, "text": "fail to accommodate employees with neurological differences", "keyword": "led to" }], "choiceAdvice": "1: 高コストで企業数減少？ 2: 神経学的差異に不適切？ 3: 伝統的デザインへ回帰願望？ 4: 定型発達者も騒音不満？", "logic": [{ "type": "text", "content": "本文(Sentence 3): 「この運動の支持者たちは、従来のオフィスは...神経学的差異を持つ従業員に対応できない(fail to accommodate)ことが多いと主張している」" }, { "type": "text", "content": "【決定要因】神経学的差異(neurological differences)を持つ従業員にオフィス環境が不適切(fail to accommodate = unsuitable)。" }, { "type": "arrow", "content": "↓" }, { "type": "text", "content": "選択肢2「標準的なオフィス環境が神経学的差異を持つ従業員には適していないことが多いという認識」と一致する。" }, { "type": "conclusion", "content": "正解: 2" }] },
    { "id": 2, "text": "What is one problem with the open-plan office design mentioned in the second paragraph?", "textTranslation": "第2段落で述べられているオープンプランオフィスデザインの問題点は何ですか？", "choices": [{ "id": 1, "text": "It discourages collaboration among employees because it creates too many distractions.", "translation": "気が散る要因が多すぎるため、従業員間のコラボレーションを妨げる。", "isCorrect": false }, { "id": 2, "text": "It relies on natural lighting, which is often insufficient for detailed work during the winter months.", "translation": "自然光に頼っているが、冬季には詳細な作業には不十分なことが多い。", "isCorrect": false }, { "id": 3, "text": "It is based on the sensory needs of the average person and ignores those who are sensitive to stimuli.", "translation": "平均的な人の感覚的ニーズに基づいており、刺激に敏感な人を無視している。", "isCorrect": true, "highlight": "based on the sensory needs of the average person" }, { "id": 4, "text": "It is often too expensive for smaller companies to implement effectively compared to traditional layouts.", "translation": "従来のレイアウトと比較して小規模企業には効果的に実装するには高すぎることが多い。", "isCorrect": false }], "hint": { "paragraphId": 2, "description": "第2段落。オープンプランオフィスの問題点を探しましょう。", "targetSentenceId": 6, "highlightWord": "is based on the sensory tolerance of the \"neurotypical\" or average person", "highlightWordSentenceId": 6 }, "keywords": ["problem", "open-plan office design", "second paragraph"], "keywordExplanations": { "problem": "問題点。", "open-plan office design": "オープンプランオフィスデザイン。" }, "keywordMatches": [{ "sentenceId": 6, "text": "is based on the sensory tolerance of the \"neurotypical\" or average person", "keyword": "problem" }, { "sentenceId": 8, "text": "hypersensitive to sensory stimuli", "keyword": "problem" }], "choiceAdvice": "1: コラボレーションを妨げる？ 2: 自然光が不十分？ 3: 平均的な人に基づき敏感な人を無視？ 4: 小企業には高すぎる？", "logic": [{ "type": "text", "content": "本文(Sentence 6): 「このレイアウトは、『定型発達』または平均的な人(average person)の感覚的許容度に基づいている(is based on)」" }, { "type": "text", "content": "本文(Sentence 8): 「感覚刺激に過敏な人々(hypersensitive)にとって、これらの要素は圧倒的なものとなりうる」" }, { "type": "text", "content": "【決定要因】average person(平均的な人)に基づき(based on)、hypersensitive(過敏な人)を無視(ignores)。" }, { "type": "arrow", "content": "↓" }, { "type": "text", "content": "選択肢3「平均的な人の感覚的ニーズに基づいており、刺激に敏感な人を無視している」と一致する。" }, { "type": "conclusion", "content": "正解: 3" }] },
    { "id": 3, "text": "Advocates of neurodiverse design argue against focusing on the \"standard\" user because", "textTranslation": "ニューロダイバースデザインの支持者が「標準的な」ユーザーに焦点を当てることに反対する理由は？", "choices": [{ "id": 1, "text": "it is impossible to define what a standard user is in today's diverse workforce.", "translation": "今日の多様な労働力において標準的なユーザーとは何かを定義することは不可能だから。", "isCorrect": false }, { "id": 2, "text": "doing so fails to acknowledge the fact that people process sensory information in different ways.", "translation": "そうすることは、人々が感覚情報を異なる方法で処理するという事実を認めないことになるから。", "isCorrect": true, "highlight": "fails to acknowledge ... people process sensory information in different ways" }, { "id": 3, "text": "most employees prefer to have a fixed desk rather than moving between different work zones.", "translation": "ほとんどの従業員は異なるワークゾーン間を移動するよりも固定席を好むから。", "isCorrect": false }, { "id": 4, "text": "architects usually do not have enough data to determine what the average preferences are.", "translation": "建築家は通常、平均的な好みを決定するのに十分なデータを持っていないから。", "isCorrect": false }], "hint": { "paragraphId": 3, "description": "第3段落。なぜ「標準的な」ユーザーに焦点を当てることに反対するかを探しましょう。", "targetSentenceId": 10, "highlightWord": "human brains process information differently", "highlightWordSentenceId": 10 }, "keywords": ["argue against", "standard user", "because"], "keywordExplanations": { "argue against": "〜に反対する。", "because": "理由を問う。" }, "keywordMatches": [{ "sentenceId": 9, "text": "rejects the idea of a \"standard\" user", "keyword": "argue against" }, { "sentenceId": 10, "text": "human brains process information differently", "keyword": "because" }], "choiceAdvice": "1: 標準を定義不可能？ 2: 感覚情報を異なる方法で処理？ 3: 固定席を好む？ 4: データ不足？", "logic": [{ "type": "text", "content": "本文(Sentence 9): 「ニューロダイバースデザインは『標準的な』ユーザーという概念を拒否する(rejects)」" }, { "type": "text", "content": "本文(Sentence 10): 「支持者たちは、人間の脳が情報を異なる方法で処理する(process information differently)ことを認識することで...」" }, { "type": "text", "content": "【決定要因】脳が情報を異なる方法で処理する(process differently)→ 選択肢2のprocess sensory information in different waysと対応。" }, { "type": "arrow", "content": "↓" }, { "type": "text", "content": "選択肢2「人々が感覚情報を異なる方法で処理するという事実を認めないことになるから」と一致する。" }, { "type": "conclusion", "content": "正解: 2" }] },
    { "id": 4, "text": "Which of the following statements best describes the impact of neurodiverse design?", "textTranslation": "ニューロダイバースデザインの影響を最もよく表している文はどれですか？", "choices": [{ "id": 1, "text": "It has forced companies to spend significantly more money on construction without seeing clear benefits.", "translation": "明確なメリットを得ることなく、企業に建設にはるかに多くの費用を費やさせることを余儀なくさせた。", "isCorrect": false }, { "id": 2, "text": "It has led to a separation of neurodivergent and neurotypical employees into different buildings.", "translation": "神経発達症の従業員と定型発達の従業員を異なる建物に分離することにつながった。", "isCorrect": false }, { "id": 3, "text": "It has resulted in better work environments that benefit the entire workforce, not just neurodivergent people.", "translation": "神経発達症の人々だけでなく、全従業員に利益をもたらすより良い労働環境をもたらした。", "isCorrect": true, "highlight": "benefit the entire workforce, not just neurodivergent people" }, { "id": 4, "text": "It has caused architects to stop using virtual reality technology because it does not accurately reflect real-world sensory experiences.", "translation": "VR技術が現実世界の感覚体験を正確に反映しないため、建築家がそれを使用しなくなった。", "isCorrect": false }], "hint": { "paragraphId": 5, "description": "第5段落。ニューロダイバースデザインの影響について述べている部分を探しましょう。", "targetSentenceId": 18, "highlightWord": "universally beneficial", "highlightWordSentenceId": 18 }, "keywords": ["impact", "neurodiverse design", "best describes"], "keywordExplanations": { "impact": "影響。", "best describes": "最も良く表す。" }, "keywordMatches": [{ "sentenceId": 17, "text": "extends beyond just helping a specific group", "keyword": "impact" }, { "sentenceId": 18, "text": "universally beneficial", "keyword": "impact" }], "choiceAdvice": "1: 費用増加でメリットなし？ 2: 異なる建物に分離？ 3: 全従業員に利益？ 4: VR使用中止？", "logic": [{ "type": "text", "content": "本文(Sentence 17): 「ニューロダイバースデザインの影響は、特定の従業員グループを助けることだけにとどまらない(extends beyond just helping a specific group)；それはすべての人の労働環境を改善している(improving for everyone)」" }, { "type": "text", "content": "本文(Sentence 18): 「その原則は普遍的に有益(universally beneficial)であることが証明されている」" }, { "type": "text", "content": "【決定要因】for everyone（すべての人）= the entire workforce（全従業員）。not just a specific group = not just neurodivergent people。" }, { "type": "arrow", "content": "↓" }, { "type": "text", "content": "選択肢3「神経発達症の人々だけでなく、全従業員に利益をもたらすより良い労働環境をもたらした」と一致する。" }, { "type": "conclusion", "content": "正解: 3" }] }
];

// Add summaryForInstructors
baseData.summaryForInstructors = {
    "title": "Designing for Neurodiversity（ニューロダイバーシティのためのデザイン）",
    "intro": "職場環境を神経多様性の観点から再設計する「ニューロダイバースデザイン」運動について解説したパッセージ。オープンプランオフィスの問題点、新しいデザイン哲学の原則、具体的な実践例、そしてすべての従業員への普遍的な恩恵について論じています。",
    "points": [
        { "label": "1. 運動の出現（第1段落）", "text": "近年、「ニューロダイバースデザイン」という運動が出現。支持者は従来のオープンプランオフィスが騒音やプライバシー欠如により、自閉症・ADHD・失読症などの神経学的差異を持つ従業員に対応できていないと主張。" },
        { "label": "2. オープンプランの問題点（第2段落）", "text": "オープンプランオフィスは「定型発達」または平均的な人の感覚的許容度に基づいて設計されている。大多数には対処可能な煩わしさでも、感覚刺激に過敏な神経発達症の人々には圧倒的で、深刻な不安や生産性低下を招く。" },
        { "label": "3. 新しいデザイン哲学（第3段落）", "text": "ニューロダイバースデザインは「標準的な」ユーザーという概念を拒否。人間の脳が情報を異なる方法で処理することを認識し、神経発達症の従業員に適応を強制するのではなく、多様な感覚体験を提供する柔軟な環境を作ることを提案。" },
        { "label": "4. 具体的な実践例（第4段落）", "text": "「静寂ゾーン」「集中ルーム」の設置、ちらつく照明や模様入りカーペットなどのトリガー特定、吸音材・調節可能な照明・プライベートポッドの設置。VRシミュレーションで建設前にスタッフがレイアウトをテストしフィードバック。" },
        { "label": "5. 普遍的な恩恵（第5段落）", "text": "ニューロダイバースデザインの影響は特定グループを超え、すべての人の労働環境を改善。原則は普遍的に有益であることが証明されている。柔軟性・快適さ・個人の選択を優先することで全労働者が環境をコントロール可能に。" }
    ]
};

// Save complete JSON
fs.writeFileSync(basePath, JSON.stringify(baseData, null, 4), 'utf8');
console.log('✅ Created complete neurodiversity_complete.json');

// Append to readingData.js
const readingDataPath = path.resolve(__dirname, 'src/data/readingData.js');
let content = fs.readFileSync(readingDataPath, 'utf8');

const lastBracketIndex = content.lastIndexOf('];');
if (lastBracketIndex === -1) {
    console.error('Could not find the end of the array (];) in readingData.js');
    process.exit(1);
}

let hasComma = false;
for (let i = lastBracketIndex - 1; i >= 0; i--) {
    const char = content[i];
    if (/\s/.test(char)) continue;
    if (char === ',') hasComma = true;
    break;
}

const newDataString = JSON.stringify(baseData, null, 4);
let insertion = hasComma ? '\n    ' + newDataString : ',\n    ' + newDataString;
const newContent = content.substring(0, lastBracketIndex) + insertion + '\n' + content.substring(lastBracketIndex);

fs.writeFileSync(readingDataPath, newContent, 'utf8');
console.log('✅ Successfully appended Designing for Neurodiversity (問題10) data to readingData.js!');
